### ISSUE TITLE
Open specific file

### ISSUE THREAD

**Issue by krishnagogada** [hanl00/theia-switch-workspace#6]
Hi @hanl00,

Is this switch-workspace is useful to open a specific file. My use case is, In a input field we give a /path / , when we click submit button automatically that should be open in theia. Is this possible? Using this switch-workshop can we achieve?

**Comment by hanl00** [comment]
I've yet to try it on opening a specific file, I've developed this to open a specific folder given its path.  I believe it should be possible to open a specific file with minor code changes
